// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfqqfarcfnskvbvyqvze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcXFmYXJjZm5za3ZidnlxdnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Nzk5NDksImV4cCI6MjA2MDI1NTk0OX0.3iUAyLCRF_qO_dSbrVNlMuMhZxe2cvLPXBbAiLRw6Lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);